name = "Zombie's Smorgasbord 1.20.1"
author = "MrFastZombie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dfdae2918daa9aa8d5bd1234c093007d299de74120ce3d22fef3343f37e1dff"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.100"

[options]
acceptable-game-versions = []
datapack-folder = "./config/paxi/datapacks"
