name = "Zombie's Smorgasbord 1.20.1"
author = "MrFastZombie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b04e46d0913f4394bd5c28b1a15ee20726b9fc9fc2bf6f5eba121e71e32f259"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.84"

[options]
acceptable-game-versions = []
