name = "Zombie's Smorgasbord 1.20.1"
author = "MrFastZombie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f4b08a7971e46ff7f12a07292785b9a5c47a7b5e664f695781686eb4663b3cc"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.100"

[options]
acceptable-game-versions = []
datapack-folder = "./config/paxi/datapacks"
