name = "Zombie's Smorgasbord 1.20.1"
author = "MrFastZombie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b79f8d48c11a0ee0582532d65efba609bdff8fb2c24a929227fec68408a88ec"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.100"

[options]
acceptable-game-versions = []
datapack-folder = "./config/paxi/datapacks"
