name = "Zombie's Smorgasbord 1.20.1"
author = "MrFastZombie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0e7e1c7c9a74dcba56820986abfe14ffd22959fd37e3b0816936656c3e99906"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
datapack-folder = "./config/paxi/datapacks"
